version: '3.8'

services:
  buscador-salud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buscador_inteligente_salud
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      # Montar el directorio de datasets para persistir datos
      - ./datasets:/app/datasets
      # Montar caché de modelos para acelerar el despliegue
      - ./models_cache:/app/models_cache
    environment:
      # Agregar variables de entorno
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
