[theme]
primaryColor = "#6aa36f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 7860

[browser]
gatherUsageStats = false
